spring:
  task: 
    execution: 
      pool: 
        core-size: 32
        max-size: 32
      thread-name-prefix: async-task-

hazelcast:
  port: 5701
  instancename: hz_inst
  restclientenabled: false
  operation-call-timeout: 30000
  initial-min-cluster-size: 0
  partitioncount: 571
  operationthreadcount: 8
  maxjoinseconds: 300
  heartbeat-interval-seconds: 15
  max-no-heartbeat-seconds: 240
  memberlistpublish-interval-seconds: 60
  masterconfirmation-interval-seconds: 30
  operation-responsequeue-idlestrategy: block
  backpressure-enabled: true
  backpressure-partition: 200
  clientengine-query-count: 20
  client-endpointremove-delay: 180
  diagnostics-enabled: false
  event-queue-capacity: 3000000
  write-behind-queue-capacity: 15000
  io-thread-count: 3
  shutdownhook-enabled: false
  statisticsprintduration: 60
  mancenter:
    enabled: false
    url: http://localhost:8080/hazelcast-mancenter
  mapconfig:
    personMap:
     backupcount: 0
     evictionpolicy: LFU
     timetolive: 172800
     writetocassandra: true
     maxentriespernode: 500000
  clustermembers: localhost:8080,localhost:5702
  consul-discovery:
    enabled: false
    url:

cassandra-config:
  contact-points: 127.0.0.1
  port: 9042
  keyspace-name: einv_im_dev
  username: cassandra
  password: cassandra
  datacenter: dc1

feign:
  client:
    config:
      consul:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        encoder: feign.gson.GsonEncoder
        decoder: feign.gson.GsonDecoder

